name: Build

on:
  push:
  pull_request:

jobs:

  build:
    name: Build (${{ matrix.os_name }})
    env:
      GO_VERSION: 1.22
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            os_name: linux
          - os: windows-latest
            os_name: windows
          - os: macos-latest
            os_name: macos
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install dependencies
        run: go mod download
      - name: Test
        run: go test -v
      - name: Build
        run: go build -v
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rogueserver-${{ matrix.os_name }}-${{ github.sha }}
          path: |
            rogueserver*
            !rogueserver.go
